mm_samychan_backend_package_upload:
    path:     /upload/
    defaults: { _controller: MMSamyChanBackendBundle:Upload:upload }

mm_samychan_backend_package_upload_json:
    path:     /upload.json
    defaults: { _controller: MMSamyChanBackendBundle:Upload:uploadJson }

mm_samychan_backend_package:
    path:     /{hash}.json
    defaults: { _controller: MMSamyChanBackendBundle:ScmPackage:index }

mm_samychan_backend_package_download:
    path:     /{hash}/download/
    defaults: { _controller: MMSamyChanBackendBundle:ScmPackage:download }

mm_samychan_backend_file:
    path:     /{hash}/file/{scmFileId}/
    defaults: { _controller: MMSamyChanBackendBundle:ScmFile:file }

mm_samychan_backend_favorites:
    path:     /{hash}/favorites/{favNo}.json
    methods:  [GET]
    defaults: { _controller: MMSamyChanBackendBundle:ScmFavorite:index }

mm_samychan_backend_favorites_post:
    path:     /{hash}/favorites/{favNo}.json
    methods:  [POST]
    defaults: { _controller: MMSamyChanBackendBundle:ScmFavorite:indexPost, _format: json }

mm_samychan_backend_file_json:
    path:     /{hash}/file/{scmFileId}/json/
    defaults: { _controller: MMSamyChanBackendBundle:ScmFile:fileJson }

mm_samychan_backend_file_export:
    path:     /{hash}/file/{scmFileId}/csv/
    defaults: { _controller: MMSamyChanBackendBundle:ScmFile:fileExport }

mm_samychan_backend_file_reorder:
    path:     /{hash}/file/{scmFileId}/reorder/
    defaults: { _controller: MMSamyChanBackendBundle:ScmFile:fileReorder }

mm_samychan_backend_channels:
    path:     /{hash}/channels.json
    defaults: { _controller: MMSamyChanBackendBundle:ScmChannel:channels }

mm_samychan_backend_demo_load:
    path:     /demo/load/
    defaults: { _controller: MMSamyChanBackendBundle:Demo:load }

mm_samychan_backend_settings_import_post:
    path:     /{hash}/import-settings.json
    methods:  [POST]
    defaults: { _controller: MMSamyChanBackendBundle:SettingsImport:importSettingsPost, _format: json }